module.exports.gl_entry_list = [
    "job_id",
    "transaction_id",
    "service",
    "transaction_account_type",
    "dr_cr",
    "accounting_type",
    "account_sequence",
    "before_prin_balance",
    "transaction_amount",
    "after_prin_balance",
    "currency",
    "base_amount",
    "base_currency",
    "account_branch",
    "service_branch",
    "cost_center",
    "business_area",
    "profit_center",
    "clearing_and_settlement_key",
    "product_name",
    "customer_type",
    "accounting_status",
    "gl_account_number",
    "business_product",
    "account_number",
    "transaction_sequence",
    "transaction_datetime",
    "transaction_date",
    "channel_post_date",
    "datetime_stamp",
    "other_prop",
    "chrono_sequence",
    "original_reversed_job_id",
    "transaction_sequence_ref",
    //     "trnRef",
    //     "before_balance",
    //     "first_payment_date",
    //     "installment_amount",
    //     "number_of_payment",
    //     "interest_index",
    //     "interest_spread"
]
